---
abstract: 'Plack login application.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  CSS::Struct::Output::Indent: 0
  ExtUtils::MakeMaker: 6.59
  HTTP::Request: 0
  Plack::Test: 0
  Tags::Output::Indent: 0
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-App-Login
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  CSS::Struct::Output::Raw: 0
  Plack::Util::Accessor: 0
  Tags::HTML::Login::Button: 0
  Tags::HTML::Page::Begin: 0.13
  Tags::HTML::Page::End: 0.04
  Tags::Output::Raw: 0
  Unicode::UTF8: 0
  perl: 5.8.0
resources:
  bugtracker: https://github.com/michal-josef-spacek/Plack-App-Login/issues
  homepage: https://github.com/michal-josef-spacek/Plack-App-Login
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/Plack-App-Login
version: '0.05'
